version: '3.8'
services:
  backend:
    image: 'frappe/erpnext-worker:v14'
    container_name: erpnext-backend
    restart: unless-stopped
    volumes:
      - 'sites:/home/frappe/frappe-bench/sites'
      - 'assets:/home/frappe/frappe-bench/sites/assets'

  configurator:
    image: 'frappe/erpnext-worker:v14'
    container_name: erpnext-configurator
    restart: no  # 'no' porque es una tarea de inicialización
    command:
      - bash
      - '-c'
      - "wait-for-it -t 120 db:3306; wait-for-it -t 120 redis:6379; python configure.py && echo 'Configuration completed' && exit 0"
    environment:
      DB_HOST: db
      DB_PORT: '3306'
      REDIS_CACHE: 'redis:6379/0'
      REDIS_QUEUE: 'redis:6379/1'
      REDIS_SOCKETIO: 'redis:6379/2'
      SOCKETIO_PORT: '9000'
    volumes:
      - 'sites:/home/frappe/frappe-bench/sites'

  create-site:
    image: 'frappe/erpnext-worker:v14'
    container_name: erpnext-create-site
    restart: no  # 'no' porque solo debe ejecutarse una vez
    volumes:
      - 'sites:/home/frappe/frappe-bench/sites'
      - 'assets:/home/frappe/frappe-bench/sites/assets'
    entrypoint:
      - bash
      - '-c'
    command:
      - "wait-for-it -t 120 db:3306; wait-for-it -t 120 redis:6379; export start=`date +%s`; until [[ -n `grep -hs ^ common_site_config.json | jq -r \".db_host // empty\"` ]] && [[ -n `grep -hs ^ common_site_config.json | jq -r \".redis_cache // empty\"` ]] && [[ -n `grep -hs ^ common_site_config.json | jq -r \".redis_queue // empty\"` ]]; do echo \"Waiting for common_site_config.json to be created\"; sleep 10; if (( `date +%s`-start > 300 )); then echo \"could not find common_site_config.json with required keys\"; exit 1; fi; done; echo \"common_site_config.json found\"; if bench site-exists frontend; then echo \"Site frontend already exists, exiting\"; exit 0; else bench new-site frontend --admin-password=admin123 --mariadb-root-password=erpnext123 --install-app erpnext; fi;"

  db:
    image: 'mariadb:10.6'
    container_name: erpnext-db
    healthcheck:
      test: 'mysqladmin ping -h localhost --password=erpnext123'
      interval: 5s
      retries: 20
    restart: unless-stopped
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
      - '--skip-character-set-client-handshake'
      - '--skip-innodb-read-only-compressed'
    environment:
      MYSQL_ROOT_PASSWORD: erpnext123
    volumes:
      - 'db-data:/var/lib/mysql'

  frontend:
    image: 'frappe/erpnext-nginx:v14'
    container_name: erpnext-frontend
    restart: unless-stopped
    environment:
      BACKEND: 'backend:8000'
      FRAPPE_SITE_NAME_HEADER: frontend
      SOCKETIO: 'websocket:9000'
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: 'off'
    volumes:
      - 'sites:/usr/share/nginx/html/sites'
      - 'assets:/usr/share/nginx/html/assets'
    ports:
      - '8081:8080'

  queue-default:
    image: 'frappe/erpnext-worker:v14'
    container_name: erpnext-queue-default
    restart: unless-stopped
    command:
      - bench
      - worker
      - '--queue'
      - default
    volumes:
      - 'sites:/home/frappe/frappe-bench/sites'

  queue-long:
    image: 'frappe/erpnext-worker:v14'
    container_name: erpnext-queue-long
    restart: unless-stopped
    command:
      - bench
      - worker
      - '--queue'
      - long
    volumes:
      - 'sites:/home/frappe/frappe-bench/sites'

  queue-short:
    image: 'frappe/erpnext-worker:v14'
    container_name: erpnext-queue-short
    restart: unless-stopped
    command:
      - bench
      - worker
      - '--queue'
      - short
    volumes:
      - 'sites:/home/frappe/frappe-bench/sites'

  redis:
    image: 'redis:6.2-alpine'
    container_name: erpnext-redis
    restart: unless-stopped
    volumes:
      - 'redis-data:/data'

  scheduler:
    image: 'frappe/erpnext-worker:v14'
    container_name: erpnext-scheduler
    restart: unless-stopped
    command:
      - bench
      - schedule
    volumes:
      - 'sites:/home/frappe/frappe-bench/sites'

  websocket:
    image: 'frappe/frappe-socketio:v14'
    container_name: erpnext-websocket
    restart: unless-stopped
    volumes:
      - 'sites:/home/frappe/frappe-bench/sites'

volumes:
  assets: null
  db-data: null
  redis-data: null
  sites: null